<?php
$functions = array(
    'ael_gamification_get_ranking' => array(
        'classname' => 'ael_gamification_external',
        'methodname' => 'get_position_ranking',
        'classpath' => 'blocks/ael_gamification/externallib.php',
        'description' => 'Return position ranking user ',
        'type' => 'read',
       // 'capabilities' => 'moodle/course:view, moodle/course:update, moodle/course:viewhiddencourses',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'ael_gamification_get_point' => array(
        'classname' => 'ael_gamification_external',
        'methodname' => 'get_point',
        'classpath' => 'blocks/ael_gamification/externallib.php',
        'description' => 'Return point user ',
        'type' => 'read',
       // 'capabilities' => 'moodle/course:view, moodle/course:update, moodle/course:viewhiddencourses',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'ael_gamification_get_medal' => array(
        'classname' => 'ael_gamification_external',
        'methodname' => 'get_medal',
        'classpath' => 'blocks/ael_gamification/externallib.php',
        'description' => 'Return medal user ',
        'type' => 'read',
       // 'capabilities' => 'moodle/course:view, moodle/course:update, moodle/course:viewhiddencourses',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'ael_gamification_get_progress' => array(
        'classname' => 'ael_gamification_external',
        'methodname' => 'get_progress',
        'classpath' => 'blocks/ael_gamification/externallib.php',
        'description' => 'Return progress ',
        'type' => 'read',
       // 'capabilities' => 'moodle/course:view, moodle/course:update, moodle/course:viewhiddencourses',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'ael_gamification_get_rancking_type' => array(
        'classname' => 'ael_gamification_external',
        'methodname' => 'get_rancking',
        'classpath' => 'blocks/ael_gamification/externallib.php',
        'description' => 'Return rancking ',
        'type' => 'read',
       // 'capabilities' => 'moodle/course:view, moodle/course:update, moodle/course:viewhiddencourses',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'ael_gamification_get_badges' => array(
        'classname' => 'ael_gamification_external',
        'methodname' => 'get_badges',
        'classpath' => 'blocks/ael_gamification/externallib.php',
        'description' => 'Return badges ',
        'type' => 'read',
       // 'capabilities' => 'moodle/course:view, moodle/course:update, moodle/course:viewhiddencourses',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    )
);

